//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedTickets.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieBookingDetailsEntities : DbContext
    {
        public MovieBookingDetailsEntities()
            : base("name=MovieBookingDetailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblLocation> tblLocations { get; set; }
        public virtual DbSet<tblMovy> tblMovies { get; set; }
        public virtual DbSet<tblTheater> tblTheaters { get; set; }
        public virtual DbSet<tblLanguage> tblLanguages { get; set; }
    }
}
