//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedTickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovy
    {
        public int MovieId { get; set; }
        public string Movie { get; set; }
        public string Description { get; set; }
        public string MovieType { get; set; }
    }
}
