//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedTickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTheater
    {
        public int TheaterId { get; set; }
        public string Theater { get; set; }
        public string TheaterType { get; set; }
        public string Comments { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
    }
}
